name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: docker-compose up -d

      - name: Wait for services
        run: echo "Waiting for services to be ready..."
             sleep 30

      - name: Test application with curl
        run: curl localhost:81/index.php

      - name: Stop Docker Compose
        if: always()
        run: |
          docker-compose -f docker-compose.yml down

